// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagement.Infrastructure.Data;

#nullable disable

namespace TaskManagement.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagement.Core.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 11, 14, 12, 55, 28, 933, DateTimeKind.Utc).AddTicks(8646),
                            Email = "admin@example.com",
                            Name = "Admin User",
                            Role = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2025, 11, 14, 12, 55, 28, 933, DateTimeKind.Utc).AddTicks(8647),
                            Email = "john@example.com",
                            Name = "John Doe",
                            Role = "User"
                        });
                });

            modelBuilder.Entity("TaskManagement.Core.Entities.WorkTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.ToTable("WorkTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssignedToUserId = 1,
                            CreatedAt = new DateTime(2025, 11, 14, 12, 55, 28, 933, DateTimeKind.Utc).AddTicks(8772),
                            Description = "Initialize database schema",
                            Status = "Completed",
                            Title = "Setup Database",
                            UpdatedAt = new DateTime(2025, 11, 14, 12, 55, 28, 933, DateTimeKind.Utc).AddTicks(8772)
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 2,
                            CreatedAt = new DateTime(2025, 11, 14, 12, 55, 28, 933, DateTimeKind.Utc).AddTicks(8774),
                            Description = "Implement REST API endpoints",
                            Status = "InProgress",
                            Title = "Build API",
                            UpdatedAt = new DateTime(2025, 11, 14, 12, 55, 28, 933, DateTimeKind.Utc).AddTicks(8775)
                        },
                        new
                        {
                            Id = 3,
                            AssignedToUserId = 2,
                            CreatedAt = new DateTime(2025, 11, 14, 12, 55, 28, 933, DateTimeKind.Utc).AddTicks(8776),
                            Description = "Build Angular application",
                            Status = "Pending",
                            Title = "Create Frontend",
                            UpdatedAt = new DateTime(2025, 11, 14, 12, 55, 28, 933, DateTimeKind.Utc).AddTicks(8777)
                        });
                });

            modelBuilder.Entity("TaskManagement.Core.Entities.WorkTask", b =>
                {
                    b.HasOne("TaskManagement.Core.Entities.User", "AssignedToUser")
                        .WithMany("Tasks")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedToUser");
                });

            modelBuilder.Entity("TaskManagement.Core.Entities.User", b =>
                {
                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
